title: Nagymaros
description: Jekyll theme for a conference website
baseurl: /jekyll-nagymaros
url: https://piazzai.github.io

permalink: pretty
theme: jekyll-nagymaros

copyright: Place Holder
indexing: true

exclude:
  - LICENSE
  - README.md
